version: '3.8'

services:
  fake-email:
    container_name: fake-email
    image: reachfive/fake-smtp-server
    restart: unless-stopped
    volumes:
      - v-fake-email:/www
    ports:
      - "1025:1025"
      - "1080:1080"

volumes:
  v-fake-email:

